### ISSUE TITLE
Installed on Win7 - get fast scrolling window

### ISSUE THREAD

**Issue by tyeeman** [anasrar/Zippy-DL#2]
Just installed on Win7. I ran the command in the readme - 
```
zippydl -d https://xxxxx.zippyshare.com/v/xxxxxxxx/file.html 
```
I get a fast scrolling window that shows this command line over and over. Any tips on what's  happening?

**Comment by anasrar** [comment]
can you give me screenshot ??
please check url zippyshare that file exist

**Comment by tyeeman** [comment]
Here is a screenshot - File that shows in the screenshot does not exist but that is not the file I used in the command. I used https://www114.zippyshare.com/v/xxxxxxx/file.html

So it's getting redirected obviously to a file that does not exist but the original file - does exist if you input it in the browser.

**Comment by anasrar** [comment]
try to open with Windows PowerShell

**Comment by tyeeman** [comment]
I've never used powershell, should it work different than cmd?

Update - I had to run this in my batch file and it works! - 
```
zippydl.cmd -d "https://www114.zippyshare.com/v/xxxxxxx/file.html"
```

I'm only getting one file download at a time. It would be nice to have multiple downloads and multiple connections. Zippy does support this!

**Comment by anasrar** [comment]
just to make sure the bug is not in the cmd
