### ISSUE TITLE
Saya menginstall di termux. Tetapi tidak bisw digunakan

### ISSUE THREAD

**Issue by uluumbch** [anasrar/Zippy-DL#3]
Apa yang harus diinstall di termux untuk menggunakan tool ini?
![Screenshot_2019-08-17-09-53-37-743_com termux](https://user-images.githubusercontent.com/49960993/63205875-18e8fc80-c0d5-11e9-8d74-ac6329050ed7.png)
Saya tidak bisa menggunakannya

**Comment by anasrar** [comment]
sorry for late being response
in termux :
```
$ apt install nodejs
```
to install nodo js
after that
```
$ npm install zippydl -g
```
to install globally
if you install from clone just
```
$ npm install
```
to install all dependencies
then
```
$ npm link
```
to make it globally

**Comment by uluumbch** [comment]
thank you, it's usefull

**Comment by Uluum** [comment]
Where the file saved in termux android?
